'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, KeyRound, LockKeyhole, Mail, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react'

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const demoCode = '123456'

function Field({ label, id, type = 'text', value, onChange, placeholder, icon: Icon, error }) {
  const [visible, setVisible] = useState(false)
  const inputType = type === 'password' && visible ? 'text' : type
  return <label className="auth-field" htmlFor={id}><span>{label}</span><div className={`auth-input-wrap ${error ? 'has-error' : ''}`}><Icon size={17} aria-hidden="true" /><input id={id} type={inputType} value={value} onChange={onChange} placeholder={placeholder} aria-invalid={Boolean(error)} />{type === 'password' && <button type="button" className="input-action" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button>}</div>{error && <small className="field-error">{error}</small>}</label>
}

function Notice({ children, tone = 'info', onClose }) { return <div className={`auth-notice ${tone}`} role="alert"><span>{tone === 'success' ? <CheckCircle2 size={17} /> : <ShieldCheck size={17} />}</span><p>{children}</p>{onClose && <button onClick={onClose} aria-label="Close message"><X size={16} /></button>}</div> }

function AuthShell({ children, mode, onMode }) { return <main className="auth-page"><div className="auth-glow auth-glow-one" /><div className="auth-glow auth-glow-two" /><a href="/" className="auth-brand"><span className="logo-mark"><Sparkles size={17} /></span><span>NEXORA<span className="logo-dot">.</span></span></a><section className="auth-layout"><aside className="auth-aside"><span className="auth-kicker">NEXORA LEARNING PLATFORM</span><h1>Turn curiosity into <em>capability.</em></h1><p>One focused session at a time. Build the skills that move your future forward.</p><div className="auth-aside-list"><span><CheckCircle2 size={17} /> Expert-led courses</span><span><CheckCircle2 size={17} /> Practical projects</span><span><CheckCircle2 size={17} /> A path made for you</span></div></aside><div className="auth-card">{children}<div className="auth-switch">{mode === 'login' ? <>New to Nexora? <button onClick={() => onMode('register')}>Create an account <ArrowRight size={14} /></button></> : <>Already learning with us? <button onClick={() => onMode('login')}>Log in <ArrowRight size={14} /></button></>}</div></div></section><p className="auth-footer">© 2024 Nexora Learning, Inc. <span>·</span> Secure demo experience</p></main> }

function Login({ onMode, onForgot }) {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [errors, setErrors] = useState({})
  const [notice, setNotice] = useState('')
  function submit(event) { event.preventDefault(); const next = {}; if (!emailPattern.test(email)) next.email = 'Enter a valid email address.'; if (password.length < 8) next.password = 'Password must be at least 8 characters.'; setErrors(next); if (!Object.keys(next).length) { sessionStorage.setItem('nexora-auth', JSON.stringify({ email })); window.location.href = '/dashboard' } }
  return <><div className="auth-heading"><span className="auth-icon"><LockKeyhole size={20} /></span><span className="auth-kicker">WELCOME BACK</span><h2>Log in to keep learning.</h2><p>Pick up right where you left off.</p></div>{notice && <Notice onClose={() => setNotice('')}>{notice}</Notice>}<form className="auth-form" onSubmit={submit} noValidate><Field label="Email address" id="login-email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" icon={Mail} error={errors.email} /><Field label="Password" id="login-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" icon={KeyRound} error={errors.password} /><button type="button" className="forgot-link" onClick={onForgot}>Forgot password?</button><button className="auth-submit" type="submit">Log in <ArrowRight size={17} /></button></form></> }

function Register({ onMode }) {
  const [step, setStep] = useState('form'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [errors, setErrors] = useState({}); const [code, setCode] = useState(''); const [notice, setNotice] = useState(''); const [cooldown, setCooldown] = useState(0)
  useEffect(() => { if (!cooldown) return; const timer = setInterval(() => setCooldown((value) => value - 1), 1000); return () => clearInterval(timer) }, [cooldown])
  function submit(event) { event.preventDefault(); const next = {}; if (!form.name.trim()) next.name = 'Tell us your name.'; if (!emailPattern.test(form.email)) next.email = 'Enter a valid email address.'; if (form.password.length < 8) next.password = 'Use at least 8 characters.'; setErrors(next); if (!Object.keys(next).length) { setStep('otp'); setCooldown(30) } }
  function verify(event) { event.preventDefault(); if (code !== demoCode) { setNotice('That code is not valid. Use the demo code 123456.'); return } sessionStorage.setItem('nexora-profile', JSON.stringify(form)); onMode('login') }
  if (step === 'otp') return <><div className="auth-heading"><span className="auth-icon"><Mail size={20} /></span><span className="auth-kicker">VERIFY YOUR EMAIL</span><h2>Check your inbox.</h2><p>We sent a six-digit code to <strong>{form.email}</strong>.</p></div>{notice && <Notice tone="error" onClose={() => setNotice('')}>{notice}</Notice>}<form className="auth-form" onSubmit={verify}><label className="auth-field"><span>Verification code</span><input className="otp-input" inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" autoFocus /></label><button className="auth-submit" type="submit">Verify email <CheckCircle2 size={17} /></button><button className="resend" type="button" disabled={cooldown > 0} onClick={() => setCooldown(30)}>{cooldown ? `Resend code in ${cooldown}s` : 'Resend code'}</button><p className="demo-hint">Demo code: <strong>123456</strong></p></form></>
  return <><div className="auth-heading"><span className="auth-icon"><UserRound size={20} /></span><span className="auth-kicker">START YOUR JOURNEY</span><h2>Create your account.</h2><p>Join thousands of curious learners building what&apos;s next.</p></div>{notice && <Notice tone="error" onClose={() => setNotice('')}>{notice}</Notice>}<form className="auth-form" onSubmit={submit} noValidate><Field label="Full name" id="register-name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Alex Morgan" icon={UserRound} error={errors.name} /><Field label="Email address" id="register-email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" icon={Mail} error={errors.email} /><Field label="Password" id="register-password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" icon={KeyRound} error={errors.password} /><button className="auth-submit" type="submit">Create account <ArrowRight size={17} /></button></form></> }

function ResetModal({ onClose }) { const [step, setStep] = useState('email'); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [cooldown, setCooldown] = useState(0); useEffect(() => { if (!cooldown) return; const timer = setInterval(() => setCooldown((value) => value - 1), 1000); return () => clearInterval(timer) }, [cooldown]); function send(e) { e.preventDefault(); if (!emailPattern.test(email)) { setError('Enter a valid email address.'); return } setError(''); setStep('reset'); setCooldown(30) } function reset(e) { e.preventDefault(); if (code !== demoCode || password.length < 8) { setError(code !== demoCode ? 'Use the six-digit demo code 123456.' : 'New password must be at least 8 characters.'); return } setStep('done') } return <div className="modal-backdrop" role="presentation"><div className="reset-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><button className="modal-close" onClick={onClose} aria-label="Close dialog"><X size={18} /></button>{step === 'done' ? <div className="modal-success"><CheckCircle2 size={36} /><h2>Password updated.</h2><p>You can now log in with your new password.</p><button className="auth-submit" onClick={onClose}>Return to login</button></div> : <><span className="auth-kicker">ACCOUNT RECOVERY</span><h2 id="reset-title">Reset your password.</h2><p className="modal-copy">{step === 'email' ? 'We&apos;ll send a verification code to your email.' : `Enter the code sent to ${email} and choose a new password.`}</p>{error && <Notice tone="error">{error}</Notice>}<form className="auth-form" onSubmit={step === 'email' ? send : reset}>{step === 'email' ? <Field label="Email address" id="reset-email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" icon={Mail} /> : <><label className="auth-field"><span>Verification code</span><input className="otp-input" inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} placeholder="000000" autoFocus /></label><Field label="New password" id="new-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" icon={KeyRound} /></>}<button className="auth-submit" type="submit">{step === 'email' ? 'Send code' : 'Update password'} <ArrowRight size={17} /></button>{step === 'reset' && <button className="resend" type="button" disabled={cooldown > 0} onClick={() => setCooldown(30)}>{cooldown ? `Resend code in ${cooldown}s` : 'Resend code'}</button>}<p className="demo-hint">Demo code: <strong>123456</strong></p></form></>}</div></div> }

export default function AuthPage() { const [mode, setMode] = useState('login'); const [forgot, setForgot] = useState(false); const heading = useMemo(() => mode, [mode]); return <AuthShell mode={heading} onMode={setMode}>{mode === 'login' ? <Login onMode={setMode} onForgot={() => setForgot(true)} /> : <Register onMode={setMode} />}{forgot && <ResetModal onClose={() => setForgot(false)} />}</AuthShell> }
