'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, BookOpen, CheckCircle2, ChevronLeft, ChevronRight, Download, Lock, LogOut, Play, Sparkles } from 'lucide-react'

const catalog = [
  { id: 1, title: 'Full-Stack Web Development', category: 'Development', difficulty: 'Intermediate', description: 'Build modern web applications from interface to deployment.', price: 0, thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80', lessons: [{ title: 'The modern web stack', duration: '12 min', notes: 'Learn how the browser, server, and database work together.', video: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4' }, { title: 'Build your first interface', duration: '24 min', notes: 'Compose accessible interfaces with reusable components.', video: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4' }] },
  { id: 2, title: 'Practical Data Science', category: 'Data Science', difficulty: 'Beginner', description: 'Turn raw data into decisions with practical analysis skills.', price: 59, thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80', lessons: [{ title: 'Your data toolkit', duration: '16 min', notes: 'Set up a repeatable process for exploring datasets.', video: '' }] },
  { id: 3, title: 'Product Design Systems', category: 'Design', difficulty: 'Advanced', description: 'Create consistent, accessible systems that scale with teams.', price: 99, thumbnail: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80', lessons: [{ title: 'System foundations', duration: '20 min', notes: 'Define tokens, patterns, and principles for scale.', video: '' }] },
  { id: 4, title: 'JavaScript Essentials', category: 'Development', difficulty: 'Beginner', description: 'Master the language that powers the interactive web.', price: 0, thumbnail: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=900&q=80', lessons: [{ title: 'Functions and flow', duration: '15 min', notes: 'Write clear, composable JavaScript.', video: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4' }] },
  { id: 5, title: 'Analytics for Teams', category: 'Business', difficulty: 'Intermediate', description: 'Make better product decisions with useful analytics.', price: 0, thumbnail: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80', lessons: [{ title: 'Choose useful metrics', duration: '11 min', notes: 'Avoid vanity metrics.', video: '' }] },
]

function Header({ email, onLogout }) { return <header className="dashboard-header"><a href="/" className="logo"><span className="logo-mark"><Sparkles size={17} /></span><span>NEXORA<span className="logo-dot">.</span></span></a><div className="dashboard-user"><span>{email}</span><button onClick={onLogout} aria-label="Log out"><LogOut size={17} /></button></div></header> }

export default function StudentDashboard({ email, onLogout }) {
  const [page, setPage] = useState(1); const [course, setCourse] = useState(null)
  const visible = useMemo(() => catalog.slice((page - 1) * 4, page * 4), [page]); const totalPages = Math.ceil(catalog.length / 4)
  if (course) return <CourseDetails course={course} onBack={() => setCourse(null)} />
  return <main className="dashboard-page"><Header email={email} onLogout={onLogout} /><section className="instructor-content"><span className="auth-kicker">STUDENT WORKSPACE</span><h1>My Learning &amp; Catalog</h1><p className="student-intro">Discover practical courses and keep your learning moving forward.</p><div className="management-toolbar"><div><strong>{catalog.length}</strong><span>published courses</span></div><span>Page {page} of {totalPages}</span></div><div className="instructor-course-grid">{visible.map((item) => <article className="instructor-course-card" key={item.id}><div className="instructor-thumbnail"><img src={item.thumbnail} alt={`${item.title} thumbnail`} /><span className="status-badge">{item.price ? `$${item.price.toFixed(2)}` : 'Free'}</span></div><div className="instructor-course-body"><div className="course-tags"><span>{item.category}</span><span>{item.difficulty}</span></div><h2>{item.title}</h2><p>{item.description}</p><div className="course-footer"><span>{item.lessons.length} lessons</span><button className="button" onClick={() => setCourse(item)}>View Course <ChevronRight size={15} /></button></div></div></article>)}</div><div className="pagination"><button className="button button-secondary" disabled={page === 1} onClick={() => setPage(page - 1)}><ChevronLeft size={15} /> Previous</button><span>Page {page} of {totalPages}</span><button className="button button-secondary" disabled={page === totalPages} onClick={() => setPage(page + 1)}>Next <ChevronRight size={15} /></button></div></section></main>
}

function CourseDetails({ course, onBack }) { const [enrolled, setEnrolled] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [active, setActive] = useState(0); const lesson = course.lessons[active]; const enroll = async () => { setLoading(true); await new Promise((resolve) => setTimeout(resolve, 800)); setEnrolled(true); setLoading(false); setMessage('You are enrolled. All course materials are now unlocked.') }; const selectLesson = (index) => { if (!enrolled) { setMessage('Access Denied: You must be enrolled to view this lesson.'); return } setActive(index); setMessage('') }; return <main className="dashboard-page"><Header email="Student workspace" onLogout={() => {}} /><section className="instructor-content"><button className="text-link back-link" onClick={onBack}><ArrowLeft size={15} /> Back to courses</button><div className="detail-hero"><img src={course.thumbnail} alt={`${course.title} thumbnail`} /><div><span className="auth-kicker">{course.category} · {course.difficulty}</span><h1>{course.title}</h1><p>{course.description}</p><button className="button enrollment-button" disabled={loading || enrolled || course.price > 0} onClick={enroll}>{loading ? 'Enrolling...' : enrolled ? 'Enrolled' : course.price > 0 ? 'Paid Enrollment Coming Soon' : 'Enroll Now for Free'}</button></div></div>{message && <div className={`course-alert ${enrolled ? 'success' : 'error'}`} role="status">{enrolled ? <CheckCircle2 size={17} /> : <Lock size={17} />}{message}</div>}<div className="lesson-layout"><aside className="lesson-sidebar"><span className="auth-kicker">SYLLABUS</span><h2>{course.lessons.length} lessons</h2>{course.lessons.map((item, index) => <button className={`lesson-item ${enrolled && active === index ? 'active' : ''}`} key={item.title} onClick={() => selectLesson(index)}>{enrolled ? <Play size={14} /> : <Lock size={14} />}<span><strong>{item.title}</strong><small>{item.duration}</small></span></button>)}</aside><div className="lesson-main">{enrolled ? <><div className="video-frame"><video controls poster={course.thumbnail} src={lesson.video}><track kind="captions" /></video></div><div className="notes-panel"><div><BookOpen size={18} /><strong>{lesson.title}</strong></div><p>{lesson.notes}</p><a className="text-link" href="#notes" onClick={(event) => event.preventDefault()}><Download size={15} /> Download Notes.pdf</a></div></> : <div className="locked-player"><Lock size={28} /><strong>Enrolled Students Only</strong><p>Please enroll to access video content.</p></div>}</div></div></section></main> }
